### ISSUE TITLE
Attempt to remove scipy dependency

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/exsim#6]
It looks like `scipy` is used only for some constants. `scipy` is a big dependency and it might be worth removing it.

**Comment by lang-m** [comment]
`scipy` is currently also a dependency of `discretisedfield` (used in `discretisedfield.tools`, `scipy.ndimage` is used) and `micromagnetictests` (used in `stdprob3`, `scipy.optimize.bisect`is used)

**Comment by marijanbeg** [comment]
Good point! Thanks @lang-m.
